### ISSUE TITLE
Can't make it work with docker-compose

### ISSUE THREAD

**Issue by BHMath** [tynor88/docker-rclone#4]
Hi,

First thank you so much for your container this is amazing.

But I can't figure out how to make it work as a docker-compose.
You'll find my log in attachment but it seems that the script is never called when I docker-compose up my container (cf. docker-compose.log). On the other hand creating the container manually is working (cf. docker.log)

And by the way only the dev branch has the latest rclone version 1.38.

Thanks ahead for your help !

[docker.log](https://github.com/tynor88/docker-rclone/files/1485508/docker.log)
[docker-compose.yml](https://github.com/tynor88/docker-rclone/files/1485510/docker-compose.yml.txt)
[docker-compose.log](https://github.com/tynor88/docker-rclone/files/1485509/docker-compose.log)

**Comment by tynor88** [comment]
@BHMath did you set up your remotes?

**Comment by BHMath** [comment]
What do you mean by setting up my remotes ? The config should be the same since it's the same volume. I didn't start both container at the same time.

I don't know where the difference is between my two way of starting it. Could you try it on your side ?

`docker create --name=rclone -e SYNC_DESTINATION=acd -e SYNC_DESTINATION_SUBPATH=test2 -e CRON_SCHEDULE="* * * * *" -v D:\Documents\Docker\rclone\config:/config -v D:\Documents\Docker\rclone\test2:/data tynor88/rclone:dev`

```yaml
version: '3'
services:
  rclone:
    image: tynor88/rclone:dev
    container_name: rclone
    environment:
      - SYNC_DESTINATION=acd
      - SYNC_DESTINATION_SUBPATH=test2
      - CRON_SCHEDULE="* * * * *" 
    volumes:
      - D:\Documents\Docker\rclone\config:/config
      - D:\Documents\Docker\rclone\test2:/data
```
